//Ores - AddOre(entity,level,resource,skin,disabled skin,time)
AddOre("da_stone",1,"stone",0,6,2)
AddOre("da_tin",3,"tin ore",1,6,4)
AddOre("da_copper",3,"copper ore",2,6,4)
AddOre("da_iron",8,"iron ore",3,6,10)
AddOre("da_coal",16,"coal",4,6,20)
AddOre("da_mithril",24,"mithril ore",5,6,30)
AddOre("da_runeessence",3,"rune_essence",0,1,2)
AddOre("da_sandstone",5,"sandstone",0,1,5)

//AddTree(entity,level,resource,trunk,time)

AddTree("da_birch",1,"birch","models/pg_props/pg_forest/pg_birch_cut.mdl",2)
AddTree("da_willow",3,"willow","models/props_foliage/tree_stump01.mdl",5)
AddTree("da_pine",8,"pine","models/props_foliage/tree_stump01.mdl",10)
AddTree("da_teak",16,"teak","models/props_foliage/tree_stump01.mdl",20)
AddTree("da_yew",24,"yew","models/props_foliage/tree_stump01.mdl",30)


//Smith - AddSmith(material of bar,{resource, amount})

AddSmith("bronze",{"tin ore",1,"copper ore",1},1)
AddSmith("iron",{"iron ore",1},8)
AddSmith("steel",{"iron ore",1,"coal",1},16)
AddSmith("mithril",{"mithril ore",1},24)

//Forge - AddForge(material,item,+lvl,{resource,amount})
//+level means level for smith the material + x

for k,v in pairs(Smithing) do

AddForge(k,"axe",0,{k .. " bar",2})
AddForge(k,"pickaxe",1,{k .. " bar",3})
AddForge(k,"longsword",2,{k .. " bar",3})
AddForge(k,"scimitar",2,{k .. " bar",4})
AddForge(k,"2hsword",3,{k .. " bar",5})

end

//Plants - AddPlant(seed,id,model)

AddPlant("melon seed","melon","models/props_junk/watermelon01.mdl")
AddPlant("banana seed","banana","models/props/cs_italy/bananna.mdl")
AddPlant("apple seed","apple","models/jakemodels/jk_apple.mdl")

//Potions - AddPotion(id,lvl,time,resources)

AddPotion( "lhppotion", 1, 2, {"red_mushroom", 2} )
AddPotion( "hppotion", 3, 4, {"red_mushroom", 4} )

//Eatable - AddEatable(id,hunger,health)

AddEatable("melon",10,0)
AddEatable("apple",8,0)
AddEatable("banana",12,0)
AddEatable("salad",22,5)
AddEatable("fruit_dish",23,0)
AddEatable("c_sardine",7,0)
AddEatable("c_trout",14,0)
AddEatable("c_pike",20,0)
AddEatable("c_salmon",25,0)
AddEatable("c_bass",32,0)
AddEatable("c_lobster",40,0)
AddEatable("sushi",35,12)

//Fireable - AddFireable(id,time,level)

AddFireable("birch",25,1)
AddFireable("willow",40,3)
AddFireable("pine",60,8)
AddFireable("teak",80,16)
AddFireable("yew",100,24)

//Fishes - AddFish(id,weapon,lvl)
AddFish("sardine","fishing_rod",1)
AddFish("trout","fishing_rod",3)
AddFish("pike","fishing_net",8)
AddFish("salmon","fishing_net",16)
AddFish("bass","fishing_net",24)
AddFish("lobster","fishing_cage",30)

//Cookable things - AddCookable(id,level,{resource id, amount})
AddCookable("salad",1,{"melon",1,"red mushroom",1})
AddCookable("fruit_dish",2,{"banana",1,"melon",1,"apple",1})
AddCookable("c_sardine",1,{"sardine",1})
AddCookable("c_trout",3,{"trout",1})
AddCookable("c_pike",8,{"pike",1})
AddCookable("c_salmon",16,{"salmon",1})
AddCookable("c_bass",22,{"bass",1})
AddCookable("c_lobster",24,{"lobster",1})
AddCookable("sushi",20,{"trout",2,"pike",2,"salmon",2})

//Runes - AddRune(id,orb,level,{multiply})
AddRune("nature_rune","orb_of_nature",1,{1,6,13,25,34,43,61,82,99})
AddRune("solar_rune","orb_of_light",3,{1,8,16,28,43,58,76,99})
AddRune("fire_rune","orb_of_fire",5,{1,13,28,49,71,99})
AddRune("water_rune","orb_of_water",7,{1,16,31,55,77,99})
AddRune("air_rune","orb_of_air",2,{1,7,15,27,41,54,72,99})
AddRune("moon_rune","orb_of_moon",4,{1,10,18,32,47,63,79,99})

//Items - AddItem(id,name,sell,buy)
AddItem("trainingstick","Training Stick",4,38,1.2)

AddItem("bronze_longsword","Bronze Longsword",13,86,1.8)
AddItem("iron_longsword","Iron Longsword",17,113,1.9)
AddItem("steel_longsword","Steel Longsword",25,189,2.0)
AddItem("mithril_longsword","Mithril Longsword",31,315,2.2)

AddItem("bronze_2hsword","Bronze 2H Sword",15,93,2.3)
AddItem("iron_2hsword","Iron 2H Sword",19,129,2.5)
AddItem("steel_2hsword","Steel 2H Sword",26,203,2.6)
AddItem("mithril_2hsword","Mithril 2H Sword",33,337,2.9)

AddItem("bronze_scimitar","Bronze Scimitar",14,90,1.7)
AddItem("iron_scimitar","Iron Scimitar",18,135,1.8)
AddItem("steel_scimitar","Steel Scimitar",26,206,1.9)
AddItem("mithril_scimitar","Mithril Scimitar",32,321,2.1)

AddItem("test_bow","Test Bow",1,1,1.1)
AddItem("staff","Staff",1,1,1.1)

AddItem("banana seed","Banana Seed",3,16,0.03)
AddItem("apple seed","Apple Seed",2,13,0.02)
AddItem("melon seed","Melon Seed",1,13,0.02)

AddItem("red mushroom","Red Mushroom",3,21,0.1)
AddItem("melon","Melon",5,29,2.6)
AddItem("apple","Apple",6,32,0.6)
AddItem("banana","Banana",7,37,0.7)
AddItem("salad","Salad",12,83,1.2)
AddItem("fruit_dish","Fruit-dish",13,102,1.4)

AddItem("gold","Gold",0,0,0.00001)
AddItem("tinderbox","Tinderbox",1,5,0.3)
AddItem("string","String",2,13,0.2)

AddItem("birch","Birch",3,14,0.5)
AddItem("willow","Willow",6,25,0.6)
AddItem("pine","Pine",10,40,0.65)
AddItem("teak","Teak",13,52,0.5)
AddItem("yew","Yew",16,72,0.7)

AddItem("lhppotion","Little Health Potion",4,38,0.4)
AddItem("hppotion","Health Potion",8,63,0.8)

AddItem("stone_pickaxe","Stone Pickaxe",9,45,0.7)
AddItem("bronze_pickaxe","Bronze Pickaxe",16,81,1.0)
AddItem("iron_pickaxe","Iron Pickaxe",19,97,1.1)
AddItem("steel_pickaxe","Steel Pickaxe",24,121,1.15)
AddItem("mithril_pickaxe","Mithril Pickaxe",32,178,1.4)

AddItem("stone","Stone",3,12,0.6)
AddItem("tin ore","Tin Ore",7,32,0.7)
AddItem("copper ore","Copper Ore",5,21,0.8)
AddItem("iron ore","Iron Ore",10,47,0.9)
AddItem("coal","Coal",12,55,1)
AddItem("mithril ore","Mithril Ore",17,78,1.1)
AddItem("sandstone","Sandstone",5,55,0.7)

AddItem("hammer","Hammer",1,27,0.8)

AddItem("bronze bar","Bronze Bar",5,27,1.2)
AddItem("iron bar","Iron Bar",9,47,0.8)
AddItem("steel bar","Steel Bar",13,66,1.4)
AddItem("mithril bar","Mithril Bar",17,88,0.9)

AddItem("stone_axe","Stone Axe",8,41,0.75)
AddItem("bronze_axe","Bronze Axe",13,73,1.0)
AddItem("iron_axe","Iron Axe",18,92,1.1)
AddItem("steel_axe","Steel Axe",23,115,1.2)
AddItem("mithril_axe","Mintril Axe",31,170,1.3)

AddItem("fishing_net","Fishing Net",13,76,1.15)
AddItem("fishing_rod","Fishing Rod",7,40,1.3)
AddItem("fishing_cage","Fishing Cage",19,118,1.5)

AddItem("sardine","Sardine",3,11,0.4)
AddItem("trout","Trout",5,23,0.5)
AddItem("pike","Pike",6,30,0.55)
AddItem("salmon","Salmon",8,39,0.5)
AddItem("bass","Bass",10,56,0.6)
AddItem("lobster","Lobster",12,75,0.7)

AddItem("c_sardine","Cooked Sardine",5,22,0.35)
AddItem("c_trout","Cooked Trout",8,38,0.45)
AddItem("c_pike","Cooked Pike",10,49,0.50)
AddItem("c_salmon","Cooked Salmon",13,62,0.45)
AddItem("c_bass","Cooked Bass",15,77,0.55)
AddItem("c_lobster","Cooked Lobster",17,86,0.65)

AddItem("rune_essence","Rune Essence",1,12,0.2)
AddItem("fire_rune","Fire rune",1,12,0.01)
AddItem("solar_rune","Solar rune",1,12,0.01)
AddItem("water_rune","Water rune",1,12,0.01)
AddItem("nature_rune","Nature rune",1,12,0.01)
AddItem("air_rune","Air rune",1,12,0.01)
AddItem("moon_rune","Moon rune",1,12,0.01)

AddItem("staff_of_nature","Staff of nature",8,54,1.2)
AddItem("staff_of_light","Staff of light",8,54,1.2)
AddItem("staff_of_fire","Staff of fire",8,54,1.2)
AddItem("staff_of_water","Staff of water",8,54,1.2)
AddItem("staff_of_air","Staff of air",8,54,1.2)
AddItem("staff_of_moon","Staff of moon",8,54,1.2)
AddItem("crystal_staff","Crystal staff",17,73,1.5)
AddItem("master_staff","Master staff",19,94,1.5)

AddItem("orb_of_nature","Orb of nature",3,22,0.6)
AddItem("orb_of_light","Orb of light",3,22,0.6)
AddItem("orb_of_fire","Orb of fire",3,22,0.6)
AddItem("orb_of_water","Orb of water",3,22,0.6)
AddItem("orb_of_air","Orb of air",3,22,0.6)
AddItem("orb_of_moon","Orb of moon",3,22,0.6)

AddItem("bronze_medhelm","Bronze Med Helm",5,20,1)
AddItem("x","Shoulder",5,20,1)
AddItem("y","Chest",5,20,1)
AddItem("z","Foot",5,20,1)
AddItem("a","Leg",5,20,1)

//Shops - AddShop(id,name,{goods})
AddShop("garden","Gardening Shop",{"apple seed","melon seed","banana seed"})
AddShop("general","General Store",{"tinderbox","hammer","stone_pickaxe","stone_axe","trainingstick"})
AddShop("jakeshop","Supplies Vendor",{"tinderbox","apple","lhppotion","stone","bronze_scimitar"})
AddShop("island","General Store",{"tinderbox","banana","salmon"})

AddShop("darm","Arm Vendor",{"bronze_scimitar","iron_scimitar","bronze_2hsword"})
AddShop("dfood","Food Vendor",{"melon","apple_seed","melon_seed","banana_seed","sardine","c_sardine"})
AddShop("dgeneral","General Store",{"tinderbox","stone_axe","stone_pickaxe","fishing_rod"})
AddShop("smith","Smith",{"hammer","copper ore","bronze bar"})

//Tokens AddToken(id,name)
AddToken("token_of_fire","Token of Fire")
AddToken("token_of_water","Token of Water")
AddToken("token_of_storm","Token of Storm")
AddToken("token_of_lightning","Token of Lightning")

//TokenVendor AddTokenVendor(id,name,goods)
AddTVendor("test","Test Token Vendor",{"mithril_longsword","token_of_storm",25})

//TokenVendorItem AddTVItem(vendor,item,token,price)
AddTVItem("test","mithril_2hsword","token_of_storm",35)
AddTVItem("test","mithril_scimitar","token_of_storm",30)

AddTVItem("test","steel_2hsword","token_of_storm",18)
AddTVItem("test","steel_scimitar","token_of_storm",15)
AddTVItem("test","steel_longsword","token_of_storm",12)

//Weapons - AddSwep(item,skill,lvl)
AddSwep("trainingstick","attack",1)
AddSwep("stone_pickaxe","mining",1)
AddSwep("stone_axe","woodcutting",1)
AddSwep("bronze_pickaxe","mining",3)
AddSwep("bronze_axe","woodcutting",3)
AddSwep("iron_pickaxe","mining",10)
AddSwep("iron_axe","woodcutting",10)
AddSwep("steel_pickaxe","mining",20)
AddSwep("steel_axe","woodcutting",20)
AddSwep("mithril_pickaxe","mining",30)
AddSwep("mithril_axe","woodcutting",30)
AddSwep("fishing_rod","fishing",1)
AddSwep("fishing_net","fishing",8)
AddSwep("fishing_cage","fishing",20)
AddSwep("bronze_longsword","attack",1)
AddSwep("iron_longsword","attack",10)
AddSwep("steel_longsword","attack",20)
AddSwep("mithril_longsword","attack",30)
AddSwep("bronze_2hsword","attack",3)
AddSwep("iron_2hsword","attack",13)
AddSwep("steel_2hsword","attack",23)
AddSwep("mithril_2hsword","attack",33)
AddSwep("bronze_scimitar","attack",2)
AddSwep("iron_scimitar","attack",12)
AddSwep("steel_scimitar","attack",22)
AddSwep("mithril_scimitar","attack",32)
AddSwep("test_bow","attack",1)
AddSwep("staff_of_nature","intellect",1)
AddSwep("staff_of_light","intellect",2)
AddSwep("staff_of_fire","intellect",4)
AddSwep("staff_of_water","intellect",6)
AddSwep("staff_of_air","intellect",8)
AddSwep("staff_of_moon","intellect",10)
AddSwep("crystal_staff","intellect",14)
AddSwep("master_staff","intellect",20)

AddArmorBone("head","ValveBiped.Bip01_Head1")
AddArmorBone("shoulder","ValveBiped.Bip01_Spine4")
AddArmorBone("chest","ValveBiped.Bip01_Spine2")
AddArmorBone("foot","ValveBiped.Bip01_L_Foot","ValveBiped.Bip01_R_Foot")
AddArmorBone("leg","ValveBiped.Bip01_L_Thigh","ValveBiped.Bip01_R_Thigh")
AddArmorBone("cape","ValveBiped.Bip01_Neck1")

AddArmor("bronze_medhelm","head","models/jakemodels/da_medhelm.mdl",0,2.8,"defense",1,90,270,180)
AddArmor("iron_medhelm","head","models/jakemodels/da_medhelm.mdl",1,2.8,"defense",10,90,270,180)
AddArmor("steel_medhelm","head","models/jakemodels/da_medhelm.mdl",2,2.8,"defense",20,90,270,180)
AddArmor("mithril_medhelm","head","models/jakemodels/da_medhelm.mdl",3,2.8,"defense",30,90,270,180)
AddArmor("x","shoulder","models/props_junk/watermelon01.mdl",0,0,"defense",1,0,0,0)
AddArmor("y","chest","models/props_junk/watermelon01.mdl",0,0,"defense",1,0,0,0)
AddArmor("z","foot","models/props_junk/watermelon01.mdl",0,0,"defense",1,0,0,0)
AddArmor("a","leg","models/props_junk/watermelon01.mdl",0,0,"defense",1,0,0,0)
AddArmor("testcape","head","models/darkages/da_cape.mdl",1,-2,"defense",1,90,270,180)

//AddArmorMenu("type","name",x,y) - X 0-250 | Y 0-600

-- AddArmorMenu("head","Helmet",125,32)
-- AddArmorMenu("shoulder","Shoulder",,)
-- AddArmorMenu("chest","Chest",,)
-- AddArmorMenu("foot","Boots",,)
-- AddArmorMenu("leg","Leg",,)
-- AddArmorMenu("cape","Cape",,)

//Crafting - AddCraft(item,lvls,res)
AddCraft("fishing_rod",1,{"birch",2})
AddCraft("fishing_net",5,{"string",6})
AddCraft("fishing_cage",16,{"willow",2,"bronze bar",1,"string",2})
AddCraft("string",3,{"willow",1})
AddCraft("stone_pickaxe",1,{"birch",2,"stone",1})
AddCraft("stone_axe",1,{"birch",1,"stone",2})
AddCraft("staff_of_nature",1,{"birch",2,"orb_of_nature",1})
AddCraft("staff_of_light",3,{"birch",2,"orb_of_light",1})
AddCraft("staff_of_fire",6,{"birch",2,"orb_of_fire",1})
AddCraft("staff_of_water",12,{"birch",2,"orb_of_water",1})
AddCraft("staff_of_air",16,{"birch",2,"orb_of_air",1})
AddCraft("staff_of_moon",20,{"birch",2,"orb_of_moon",1})
AddCraft("crystal_staff",20,{"willow",2,"birch",2,"orb_of_nature",2})
AddCraft("master_staff",20,{"willow",2,"bronze bar",2,"orb_of_light",2})

//Magic - AddMagic(id,name,element,lvl,cd,effect,gold,runes,cb zone needed)
AddMagic("heal","Heal","nature",{1,5,10,15,20},{2.6,2.5,2.4,2.3,2.2},{8,12,17,24,37},{10,25,50,100,210},{"nature_rune",1},false)
AddMagic("regrow","Regrow","nature",{1,5,10,15,20},{4.6,4.5,4.4,4.3,4.2},{3,4,5,6,8},{10,25,50,100,210},{"nature_rune",2},false)
AddMagic("gheal","Greater Heal","nature",{2,7,12,18,23},{5.2,5,4.8,4.6,4.4},{18,26,33,42,50},{15,40,70,120,250},{"nature_rune",2},false)
AddMagic("groupheal","Group Heal","nature",{2,6,13,18,22},{5,4.6,4.5,4.2,4.0},{10,14,19,26,35},{15,30,60,110,210},{"nature_rune",3},false)
AddMagic("holy_light","Holy Light","light",{1,5,10,15,20},{1.2,1.1,1.0,0.9,0.8},{6,11,13,17,22},{10,25,50,100,210},{"solar_rune",1},true)
AddMagic("holy_blast","Holy Blast","light",{3,8,12,18,24},{6,5.5,5.4,5.2,5},{13,18,25,31,40},{20,45,85,140,260},{"solar_rune",2},true)
AddMagic("fire_circle","Fire Circle","fire",{3,8,12,18,24},{6,5.5,5.4,5.2,5},{13,18,25,31,40},{20,45,85,140,260},{"fire_rune",2,"air_rune",1},true)
AddMagic("bubble_blast","Bubble Blast","water",{3,7,11,15,20},{6,5.6,5.2,5.0,4.8},{14,19,24,30,37},{40,75,105,170,300},{"water_rune",2,"air_rune",1},true)

//Buffs - AddBuff(id,time,how many times does it repeat)
AddBuff("regrow",5,5)

//SetMobInfo(mob's id,mob_npc,visible name,attack,strength,defense,health,{item name,amount,chance[%]})
//AddBoss(boss' id,mob_npc,visible name,attack,strength,defense,health,{item name,amount,chance[%]})
SetMobInfo("diseased_zombie","npc_zombie","Diseased zombie",6,7,4,23,{"zombie_venom",1,1,25,"gold",10,26,60},Color(255,255,255,255),true)

AddBoss("atron","npc_zombie","Atron",20,24,12,125,{"bronze_scimitar",1,1,3,"gold",1,100,90,"head_of_atron",1,1,100,"token_of_storm",1,1,10})
AddBoss("raunol","npc_fastzombie","Raunol the librarian",20,24,12,125,{"bronze_2hsword",1,1,5,"gold",1,200,90,"head_of_raunol",1,1,100,"token_of_storm",1,1,20})
AddBoss("disease_carrier","npc_zombie","Disease carrier",18,18,12,100,{"zombie_venom",2,2,50,"gold",50,83,20,"staff_of_darkness",1,1,2,"token_of_storm",1,1.30})

AddBoss("head_jailer","npc_fastzombie","Head Jailer",3,4,3,45,{"gold",10,40,20,"token_of_storm",1,1,20})

SetMobInfo("mutant","npc_zombie","Mutant",4,5,4,32,{"gold",1,22,80,"orb_of_fire",1,1,10,"orb_of_light",1,1,10},Color(255,255,255,255),false)
SetMobInfo("runner","npc_fastzombie","Runner Mutant",6,5,2,32,{"gold",1,22,80,"orb_of_air",1,1,10,"orb_of_water",1,1,10},Color(255,255,255,255),true)
SetMobInfo("jumper","npc_headcrab","Jumper",4,5,1,25,{"gold",1,22,80},Color(255,255,255,255),true)
SetMobInfo("qjumper","npc_headcrab_fast","Quick Jumper",6,5,1,25,{"gold",1,22,80},Color(255,255,255,255),true)

SetMobInfo("ant","npc_headcrab","Ant",1,1,1,10,{"gold",1,15,80},Color(255,255,255,255),true)
SetMobInfo("red_ant","npc_headcrab_fast","Red Ant",2,1,1,12,{"gold",1,10,80},Color(255,0,0,255),true)
SetMobInfo("jom_jailer","npc_zombie","Jailer",3,2,1,20,{"gold",1,15,80,"orb_of_nature",1,1,5},Color(200,200,200,255),true)
SetMobInfo("jom_sjailer","npc_zombie","Stealthed Jailer",3,2,0,10,{"gold",1,10,80},Color(200,200,200,50),true)
SetMobInfo("jom_ejailer","npc_fastzombie","Elite Jailer",5,4,3,15,{"gold",1,25,80},Color(255,200,200,255),true)

SetMobInfo("test","npc_vortigaunt","Testing",1,2,2,8,{"gold",1,25,80},Color(255,255,255,255),true)

AddDungeon("jake","The Dark Jail",20)
AddDungeon("monastry","The secret monastry",8)
AddDungeon("monsterjail","Jail of monsters",1)
AddDungeon("ralael","Tomb of Ralael",32)

AddHudEntity("npc_shop","Shop",90,true)
AddHudEntity("npc_bank","Bank",90,true)
AddHudEntity("npc_magictrainer","Magic Trainer",90,true)
AddHudEntity("npc_tokenvendor","Token Vendor",90,true)
AddHudEntity("npc_dtele","Dungeon Keeper",90,true)
AddHudEntity("npc_stele","Teleporter",90,true)
AddHudEntity("npc_gtele","Teleporter",90,true)
AddHudEntity("npc_clanmaster","Clan Master",90,true)
AddHudEntity("npc_clanbank","Clan Bank",90,true)
AddHudEntity("npc_squest","Quest",90,true)
AddHudEntity("npc_tquest","Quest",90,true)

AddHudEntity("da_stone","Stone",70,false)
AddHudEntity("da_copper","Copper ore",70,false)
AddHudEntity("da_tin","Tin ore",70,false)
AddHudEntity("da_iron","Iron ore",70,false)
AddHudEntity("da_coal","Coal",70,false)
AddHudEntity("da_mithril","Mithril ore",70,false)
AddHudEntity("da_runeessence","Rune essence",70,false)

AddHudEntity("da_birch","Birch",70,false)
AddHudEntity("da_willow","Willow",70,false)
AddHudEntity("da_pine","Pine",70,false)
AddHudEntity("da_teak","Teak",70,false)
AddHudEntity("da_yew","Yew",70,false)

AddClanUpgrade("5crit","+5% Critical chance",3000)
AddClanUpgrade("5dmg","+5% Damage",3000)
AddClanUpgrade("10gold","+10% Gold from mobs",4500)
AddClanUpgrade("10cd","+10% Cooldown reduction",3500)
AddClanUpgrade("10mining","10% Faster mining",2500)
AddClanUpgrade("10woodc","10% Faster woodcutting",2500)
AddClanUpgrade("10fishing","10% Faster fishing",2500)
AddClanUpgrade("10xp","+10% XP",6000)

AddStat("mobs","Mobs Killed")
AddStat("bosses","Bosses Killed")
AddStat("elites","Elites Killed")
AddStat("plkill","Players Killed")
AddStat("damage","Damage Dealt")
AddStat("drops","Drops")
AddStat("quests","Quests Completed")
AddStat("xp","XP Gained")
AddStat("lvl","Level Gained")
AddStat("trees","Trees Chopped Out")
AddStat("ores","Rocks Mined Out")
AddStat("fishes","Fishes Caught")
AddStat("runes","Runes Used")

AddAchievement("1quest","First Quest","quests",1)
AddAchievement("5quest","Hard Working","quests",5)
AddAchievement("20quest","Quest Maniac","quests",20)
AddAchievement("1000xp","Getting Better","xp",1000)
AddAchievement("9k1xp","Over 9000!!!","xp",9001)
AddAchievement("100kxp","Losing life","xp",100000)
AddAchievement("100rune","Sorcerer's Apprentice","runes",100)
AddAchievement("1krunes","Sorcerer","runes",1000)
AddAchievement("1klvl","Like A Boss","lvl",1000)
AddAchievement("antigreen","Anti Greenpeace","trees",100)
AddAchievement("japan","Japanese???","fishes",100)
AddAchievement("dwarf","Dwarf","ores",100)
AddAchievement("mobkill","Don't Kill Me","mobs",1000)
AddAchievement("insane","Insane","plkill",100)
AddAchievement("bosskill","Problem?","bosses",50)

//AddStandPart(name,model)
AddStandPart("Bare","models/darkages/scenery/marketstand_bare.mdl")
AddStandPart("New","models/darkages/market/marketstand01.mdl")
AddStandPart("Spices 01","models/darkages/scenery/spices02.mdl")
AddStandPart("Spices 02","models/darkages/scenery/spices01.mdl")
AddStandPart("Roped fish","models/darkages/scenery/ropedfish.mdl")
AddStandPart("Rocks","models/darkages/scenery/rockformation01.mdl")
AddStandPart("Table","models/darkages/scenery/marketstand_table.mdl")
AddStandPart("Herb 01","models/darkages/scenery/herb02.mdl")
AddStandPart("Herb 02","models/darkages/scenery/herb01.mdl")
AddStandPart("Fishcrate 04","models/darkages/scenery/fishcrate03.mdl")
AddStandPart("Fishcrate 03","models/darkages/scenery/fishcrate02.mdl")
AddStandPart("Fishcrate 02","models/darkages/scenery/fishcrate01_b.mdl")
AddStandPart("Fishcrate 01","models/darkages/scenery/fishcrate01.mdl")
